
export const ADD_BOOKS = 'ADD_BOOKS'

export const SET_GET_BOOK_REQUEST_STATUS = 'SET_GET_BOOK_REQUEST_STATUS'

export const MARK_BOOK_STATUS = 'MARK_BOOK_STATUS'

export const SET_SORT_CATEGORIA = 'SET_SORT_CATEGORIA'

export const SET_SORT_READ = 'SET_SORT_READ'

export const SET_SORT_DATE = 'SET_SORT_DATE'