export const SET_USER_DATA = 'SET_USER_DATA'

export const SET_LOGIN_REQUEST_STATUS = 'SET_LOGIN_REQUEST_STATUS'

export const SET_LOGIN_DATA = 'SET_LOGIN_DATA'

export const SET_SIGNUP_REQUEST_STATUS = 'SET_SIGNUP_REQUEST_STATUS'

export const SIGNUP_USER = 'SIGNUP_USER'

export const FAILED_SIGNUP = 'FAILED_SIGNUP'